// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5hLEJiewM2X6pg6KbWbo8QIVzkWM1Jvg',
    appId: '1:219967353217:android:05bf77e975b4b58d177880',
    messagingSenderId: '219967353217',
    projectId: 'expense-tracker-a816c',
    storageBucket: 'expense-tracker-a816c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqTIGVwTVn3kv8ZL9KkOVFqZq8dNG1k5E',
    appId: '1:219967353217:ios:d80f71d980f3bbbf177880',
    messagingSenderId: '219967353217',
    projectId: 'expense-tracker-a816c',
    storageBucket: 'expense-tracker-a816c.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqTIGVwTVn3kv8ZL9KkOVFqZq8dNG1k5E',
    appId: '1:219967353217:ios:d80f71d980f3bbbf177880',
    messagingSenderId: '219967353217',
    projectId: 'expense-tracker-a816c',
    storageBucket: 'expense-tracker-a816c.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );
}
